// Build information, automatically generated by `ng-info`
const build = {
    version: "2.1.1",
    timestamp: "Thu Jan 06 2022 20:54:44 GMT+0530 (India Standard Time)",
    message: null,
    git: {
        user: null,
        branch: "development",
        hash: "8e56b3",
        fullHash: "8e56b36117907d766dc25dbe380daa1e677181ff"
    }
};

export default build;